In [1]:
import numpy as np
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x=x/np.amax(x,axis=0)
y=y/100


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [3]:
def derivative_sigmoid(x):
    return x*(1-x)


In [4]:
epoch=10
lr=0.2
inp=2
hid=3
out=1

In [5]:
wh=np.random.uniform(size=(inp,hid))
print(wh)
bh=np.random.uniform(size=(1,hid))
print(bh)
wout=np.random.uniform(size=(hid,out))
print(wout)
bout=np.random.uniform(size=(1,out))
print(bout)

[[0.99117395 0.7439941  0.20030906]
 [0.39568933 0.69323382 0.66291841]]
[[0.3719163  0.74169989 0.11992716]]
[[0.71549648]
 [0.23326898]
 [0.95816337]]
[[0.73181503]]


In [6]:
for i in range(epoch):
    hinp1=np.dot(x,wh)
    print(hinp1)
    hinp=hinp1+bh
   # print(hinp)
    hlayer_act=sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    

[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.18922989 0.79645778]
 [0.55021872 0.63312793 0.43505769]
 [1.25496683 1.20614998 0.64225466]]
[[1.05647196 1.1892

In [7]:
Eo=y-output
outgrad=derivative_sigmoid(out)
d_out=Eo*outgrad
EH=d_out.dot(wout.T)
hiddengrad=derivative_sigmoid(hlayer_act)
d_hiddenlayer=EH*hiddengrad
wout+=hlayer_act.T.dot(d_out)
wh+=x.T.dot(d_hiddenlayer)*lr
print("input\n"+str(x))
print("actual output\n"+str(y))
print("the predicted output\n",output)

input
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output
[[0.92]
 [0.86]
 [0.89]]
the predicted output
 [[0.89999033]
 [0.88479419]
 [0.89909846]]
